server:
  port: 8888
spring:
  application:
    name: rabbitmq-client
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
test:
  abc:
    instance-id: acc
