# 数据库配置
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhongyp/cloud-config.git
  application:
    name: comsumer-client
  datasource:
    # jpa
    jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialec
      generate-ddl: false
      show-sql: true
      # 格式化sql语句
      properties:
        hibernate-format_sql: true
        # 解决 hibernate multiple merge 问题
        hibernate.event.merge.entity_copy_observer: allow
      hibernate:
        ddl-auto: none
logging:
  level:
    root: INFO
