# 数据库配置
server:
  port: 12000
eureka:
  instance:
    instance-id: consumer
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
spring:
  application:
    name: comsumer-client
  profiles:
    active: dev
logging:
  level:
    root: INFO
