server:
  port: 13001
# 数据库配置
spring:
  profiles:
    active: dev
  application:
    name: user-api
logging:
  level:
    root: INFO
eureka:
  instance:
    instance-id: user-api-13001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:14001/eureka/