server:
  port: 14000
# 数据库配置
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhongyp/cloud-config
          search-paths: production
          username: zhongyp
          password: camda2209861
      label: master
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.126.99.185:35678/demo?characterEncoding=UTF-8&serverTimezone=UTC
    username: demo
    password: Roc2z2209861,
    # jpa
    jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialec
      generate-ddl: false
      show-sql: true
      # 格式化sql语句
      properties:
        hibernate-format_sql: true
        # 解决 hibernate multiple merge 问题
        hibernate.event.merge.entity_copy_observer: allow
      hibernate:
        ddl-auto: none